{*
 * Confirmation dialog with dynamic signals
 * Nette template file
 *
 * Copyright (c) 2009-2011 Lukáš Doležal @ GDMT (dolezal@gdmt.cz)
 *
 * This source file is subject to the "GNU Lesser General Public Licenee" (LGPL)
 *
 * @copyright  Copyright (c) 2009 Lukáš Doležal (dolezal@gdmt.cz)
 * @license    http://www.gnu.org/copyleft/lgpl.html  GNU Lesser General Public License
 * @link       http://nettephp.com/cs/extras/confirmation-dialog
 * @package    ConfirmationDialog
 *}

{snippet}
{if $visible}
<div {if $class != '' }class="{$class}"{/if}>
	{$question}
	{widget form}
</div>
{/if}
{/snippet}
